# Generated by Django 5.1.2 on 2024-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_feedback_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
