# Generated by Django 5.1.2 on 2024-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('CR', 'Curd'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
