# Generated by Django 5.1.2 on 2024-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
