# Generated by Django 5.1.2 on 2024-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
