# Generated by Django 5.1.2 on 2024-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('ML', 'Milk'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
