# Generated by Django 5.1.2 on 2024-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('ML', 'Milk')], max_length=2),
        ),
    ]
