# Generated by Django 5.1.2 on 2024-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('ML', 'Milk'), ('CR', 'Curd'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
