# Generated by Django 5.1.2 on 2024-12-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CR', 'Curd'), ('GH', 'Ghee'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
