# Generated by Django 5.1.2 on 2024-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('ML', 'Milk'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
