# Generated by Django 5.1.4 on 2025-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
