# Generated by Django 5.1.4 on 2025-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('CR', 'Curd'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
