# Generated by Django 5.1.4 on 2025-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('LS', 'Lassi'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
